ImageSourceDir: ../data/val2017
PREPROCESS: ""

AI_ENGINE: "NCNNEngine"
NCNNEngine:
  model_path: "../data/yolov5s.param"
  bin_path: "../data/yolov5s.bin"
  in_name: []
  out_name: []

DECODER: "Yolov5Decoder"
Yolov5Decoder:
  model_path: "../data/yolov5s.onnx"
  anchors: [[10, 13, 16, 30, 33, 23],
            [30, 61, 62, 45, 59, 119],
            [116, 90, 156, 198, 373, 326]]
  num_heads: 3
  strides: [8, 16, 32]
  num_classes: 80
  box_confidence: 0.005
  box_iou_threshold: 0.6

VISUALIZER: true